### ISSUE TITLE
Remove java.net.URL usage

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#101]
Hey @asoltysik, as we're working on API-cleanup release, could we please remove all [java.net.URL occurences](https://github.com/snowplow/iglu-scala-client/blob/master/src/main/scala/com.snowplowanalytics.iglu/client/repositories/HttpRepositoryRef.scala#L19)? Feel free to just close if this will be a part of other commit - I just want to make sure we got rid of it.

If you're wondering java.net.URL is a worst Java class ever that performs a [blocking IO](java.sun.com/j2se/1.5.0/docs/api/java/net/URL.html) (DNS resolution) in order to check that two URLs are identical or not and has many other flaws.

**Comment by asoltysik** [comment]
So right now we are using HttpURLConnection here:
https://github.com/snowplow/iglu-scala-client/blob/f815b2692f1431af7869186b1e9ac8bcaf20f376/src/main/scala/com.snowplowanalytics.iglu/client/repositories/HttpRepositoryRef.scala#L75

Should we pull scalaj instead, or hammock? @chuwy @BenFradet 

I just found there is [a quite nice http client](http://openjdk.java.net/groups/net/httpclient/intro.html) built into jdk since version 9, but IIRC we are on jdk8.

**Comment by chuwy** [comment]
Let's go with that one minimalistic so far. This weekend I tried to re-write Iglu Server from Akka HTTP to http4s (nothing personal, Ben!) and really see Server using http4s someday. With that said we probably can re-use a lot of stuff between Server and Client and might end up with http4s on client-side as well, but later.

**Comment by chuwy** [comment]
> built into jdk since version 9, but IIRC we are on jdk8.

Sorry missed this. Yes, you're right, we're on JDK8. Up to you then which one to use, but I'd like to stay as minimalistic as possible.
