### ISSUE TITLE
Bump json-schema-validator to 1.0.67

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#136]
Since 1.0.40, json-schema-validator requires metaschema to use HTTPS and no URI fragments (https://github.com/networknt/json-schema-validator/issues/273), which is a big problem for Iglu because canonical metaschema is HTTP and has URI fragment (`http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`).

**Comment by istreeter** [comment]
The recent change to json-schema-validator (networknt/json-schema-validator#400) addressed the problem of allowing non-https metaschema.  However, it still rejects metaschema URIs that end in a fragment `#` like our one does.  Therefore we are still stuck on version `1.0.39` until another fix is made to json-schema-validator.

**Comment by chuwy** [comment]
A fragment issue also seems to be fixed in https://github.com/networknt/json-schema-validator/pull/412. I'm wondering if @pondzix can try to integrate it into 2.0.0 as 1.0.39 brings a lot of outdated dependencies (jackson-2.10.0 in particular)

**Comment by pondzix** [comment]
@chuwy @istreeter

I upgraded JSV to 1.0.65 (latest) and some tests are failing. The main problem is still with `#` in URI `http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`.

While investigating this issue I tried to understand what is the role of meta schema URI in our code. Based on our and JSV code my reasoning is as follows:

* in `CirceValidator` we add mentioned iglucentral URI to 'pool' of supported meta schemas.
* During validation of schema, JSV normalizes URI of provided meta schema (in `$schema` field) and tries to find a match in a 'pool'.
* If there is a match - ok. If no match - return error.

The main problem was with the normalization of an URI as it replaced `http` with `https` and trimmed `#`. Since https://github.com/networknt/json-schema-validator/pull/400 converting to `https` can be disabled but it seems https://github.com/networknt/json-schema-validator/pull/412 doesn't change behaviour regarding `#` removal.

In our case, if incoming schema uses (all schemas use this one?):

`http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`,

after normalization (using `forceHttps` set to `false` it would remain `http`):

`https://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0`

and in our code we have in 'pool' of supported meta schemas:

`http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`

No match.

<hr>
Would that be a problem is we simply adjust (adding appropriate comment) the meta schema in our code to: 

`https://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0`

? I know `https` is not supported by iglu central, but if I understand correctly this URI is never called, so the resource doesn't have to be available. It seems its sole purpose is to provide match for incoming, normalized schema.

If this is not an option we could use:

`http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0` with `forceHttps` set to `false` 

BUT it seems it could cause problems with schemas relying on e.g. `http://json-schema.org/draft-04/schema#` as JSV uses `https://json-schema.org/draft-04/schema`. Is it possible that some schema uses such `draft-04` meta instead of the one from iglucentral?

I created simple [test](https://github.com/snowplow/iglu-scala-client/blob/360dc15b539dc91f2d35953338ead89fd162f243/modules/core/src/test/scala/com.snowplowanalytics.iglu.client/validator/TestingMetaSchemas.scala) to 'visualise' different options.

**Comment by chuwy** [comment]
Hi @pondzix! Thanks for the deep analysis!

> Is it possible that some schema uses such draft-04 meta instead of the one from iglucentral?

No, I'm pretty relaxed about this part. If it's not the canonical URI - it means it's not self-describing. If it's not self-describing - it's not an Iglu's business. Since couple of years ago we force all users to set metaschema to our canonical URI (the one with `http` and `#`). Which is good because we're sure it's only one URI we care about and which is bad because we're tightly coupled with it and changing in schemas is not an option at all (a lot of old software will fail). Even if we add a second schema (`https` an no `#`) it still means nobody will be able to use because of older versions of pipeline.

> if I understand correctly this URI is never called, so the resource doesn't have to be available

You understand it right. It's merely an id rather than an actual URL.

As of `forceHttps` - I think the answer is that we should use use it (set to `false`) and be done with it.

<hr />

**To restate the remaining problem** (which is `#`) [#412](https://github.com/networknt/json-schema-validator/pull/412) just makes the JSV to not fail, but JSV still normalizes `uri#` to `uri` and as result our canonical is not recognized.

I think the right solution is to submit a PR to upstream library. [URI RFC](https://www.rfc-editor.org/rfc/rfc3986#page-38) makes it very clear:

> The fragment component is not subject to any scheme-based normalization; thus, two URIs that differ only by the suffix "#" are considered different regardless of the scheme.

I think the upstream library should support that behaviour. @stevehu is very eager to merge bugfix PRs, so I think it's a win-win for everyone.
