### ISSUE TITLE
Use Iglu Core

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-scala-client#20]
In hindsight was a mistake to make SchemaVer ever stringly-typed

**Comment by szareiangm** [comment]
To use Iglu Core, I am trying to gather the steps needed:
- Remove `SchemaKey` and use the one from Iglu Core
- Remove `SchemaCriterion` and use the one from Iglu Core
I will update my comment if could find more things to change.

**Comment by chuwy** [comment]
Thank you @szareiangm! This one is a bit tricky because of https://github.com/snowplow/iglu/issues/364.

Problem that Iglu Client always assumes explicit `SchemaVer`, but currently in Iglu Core (it can be ["partial"](https://github.com/snowplow/iglu/issues/147)). I was planning to implement https://github.com/snowplow/iglu/issues/364 in next Iglu release and incorporate Core into Client afterwards. However, I'm totally fine about implementing it straight away. 

Could you please treat all partial `SchemaVer` (where units are `Option[Int]`) simply as:

```scala
schemaVer.model.getOrElse(throw new RuntimeException(s"Iglu Client: partial schemas are not supported [$schemaKey]")
```

This is quite safe to throw these runtime exceptions as we already sure that `SchemaVer` is valid.

Let me know if it makes sense. Otherwise your plan sounds awesome!
