### ISSUE TITLE
Fix cache for iglu repositories with low priority

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#39]
I'm running Iglu repository with my own JSON Schema for weather enrichment configuration. While enrichment process is running, my Iglu repository receives GET request for weather enrichment configuration for each event item I have.
It seems cache works only for Iglu repository with lowest priority, because if we try to create empty repository with priority 0 and full repository with priority 1, it will still flood both repositories with HTTP requests.

**Comment by fblundun** [comment]
Actually I think we may have misdiagnosed this - if the empty repository has highest priority then according to our hypothesis (that caching only fails for lower priority repos) it should only get one request per node per schema before the absence of a schema is cached, rather than being flooded with requests.

**Comment by chuwy** [comment]
You're right. Then may be repo with `0` priority treated like special one?

**Comment by chuwy** [comment]
We never were able to reproduce it and internals changed a lot since then.
